const projects = [
  {name:'GNU Health', cause:'Health', tech:['Python','Tryton','PostgreSQL'], skills:['Backend','Health IT','Docs','Localization'], url:'https://www.gnuhealth.org/', repo:'https://codeberg.org/gnuhealth', blurb:'Libre health and hospital information ecosystem: EMR, HMIS, lab/federation pieces, and public-health thinking baked in.', good:'Docs, localization, Python/Tryton modules, packaging, testing, health data workflows.'},
  {name:'OpenMRS', cause:'Health', tech:['Java','React','FHIR','MySQL'], skills:['Backend','Frontend','QA','Docs'], url:'https://openmrs.org/', repo:'https://github.com/openmrs', blurb:'Open-source medical record system used by a global community of implementers.', good:'Frontend polish, Java services, tests, reference app bugs, onboarding docs.'},
  {name:'OpenELIS Global', cause:'Health', tech:['Java','Spring','PostgreSQL','Docker'], skills:['Backend','Security','QA','DevOps'], url:'https://openelis-global.org/', repo:'https://github.com/I-TECH-UW/OpenELIS-Global-2', blurb:'Open-source laboratory information system for public health labs and lab networks.', good:'Testing, security review, workflow bugs, deployment docs, interoperability.'},
  {name:'DHIS2', cause:'Health data', tech:['Java','JavaScript','PostgreSQL','Android'], skills:['Backend','Frontend','Data','Mobile'], url:'https://dhis2.org/', repo:'https://github.com/dhis2', blurb:'Open-source health information platform for collecting, visualizing, and analyzing data at serious scale.', good:'Data visualization, analytics, Java backend, React UI, docs, integrations.'},
  {name:'Sahana Eden', cause:'Disaster response', tech:['Python','Web2py','GIS'], skills:['Backend','GIS','Docs','QA'], url:'https://sahanafoundation.org/', repo:'https://github.com/sahana/eden-legacy', blurb:'Disaster and humanitarian aid management platform for preparedness, response, recovery, and resilience.', good:'GIS workflows, issue triage, disaster-response modules, documentation, Python fixes.'},
  {name:'Ushahidi', cause:'Crisis mapping', tech:['PHP','Laravel','Vue','Maps'], skills:['Frontend','Backend','Design','QA'], url:'https://www.ushahidi.com/', repo:'https://github.com/ushahidi', blurb:'Crowdsourced reporting and mapping platform for community reports, crisis mapping, and civic data.', good:'Map UX, forms, accessibility, frontend bugs, docs, data import/export.'},
  {name:'HOT Tasking Manager', cause:'Mapping', tech:['Python','React','PostGIS','OpenStreetMap'], skills:['GIS','Frontend','Backend','Non-code'], url:'https://tasks.hotosm.org/', repo:'https://github.com/hotosm/tasking-manager', blurb:'Coordination tool for volunteers mapping buildings, roads, and places in OpenStreetMap.', good:'Mapathons, task validation, UI fixes, translations, docs, Python/React work.'},
  {name:'OpenStreetMap', cause:'Mapping', tech:['Rails','PostGIS','iD','JOSM'], skills:['Mapping','Data','Frontend','Non-code'], url:'https://www.openstreetmap.org/', repo:'https://github.com/openstreetmap', blurb:'The free editable map of the world. Humanitarian projects often build on it.', good:'Mapping, validation, editor UX, imports, docs, community support.'},
  {name:'Open Data Kit', cause:'Field data', tech:['Java','Kotlin','JavaScript','Android'], skills:['Mobile','Backend','UX','QA'], url:'https://getodk.org/', repo:'https://github.com/getodk', blurb:'Tools for collecting data anywhere, including offline and resource-constrained field work.', good:'Android fixes, form UX, docs, translations, tests, accessibility.'},
  {name:'KoBoToolbox', cause:'Field data', tech:['Python','Django','React','PostgreSQL'], skills:['Backend','Frontend','Data','Docs'], url:'https://www.kobotoolbox.org/', repo:'https://github.com/kobotoolbox', blurb:'Survey, monitoring, evaluation, and research tooling used heavily in humanitarian contexts.', good:'Forms, data exports, docs, frontend, backend reliability, translations.'},
  {name:'Open Food Facts', cause:'Food transparency', tech:['Perl','Python','Flutter','APIs'], skills:['Data','Mobile','Backend','Non-code'], url:'https://world.openfoodfacts.org/', repo:'https://github.com/openfoodfacts', blurb:'Open database of food products, ingredients, allergens, nutrition facts, and labels.', good:'Data cleanup, barcode scanning, mobile work, API clients, translations, UX.'},
  {name:'OpenAQ', cause:'Environment', tech:['Python','APIs','Data pipelines','Cloud'], skills:['Data','Backend','DevOps','Visualization'], url:'https://openaq.org/', repo:'https://github.com/openaq', blurb:'Open air quality data platform making pollution data easier to access and use.', good:'Data pipelines, API clients, visualizations, docs, reliability, data quality checks.'},
  {name:'Public Lab', cause:'Environment', tech:['Ruby','JavaScript','Docs','DIY hardware'], skills:['Frontend','Docs','Design','Non-code'], url:'https://publiclab.org/', repo:'https://github.com/publiclab', blurb:'Community science network using open tools and DIY methods for environmental monitoring.', good:'Docs, research notes, web bugs, community onboarding, low-cost tool guides.'},
  {name:'Open Referral', cause:'Social services', tech:['Data standards','APIs','JSON','Docs'], skills:['Data','Docs','Standards','Backend'], url:'https://openreferral.org/', repo:'https://github.com/openreferral', blurb:'Standards and open tools for sharing information about health, human, and social services.', good:'Schema docs, API examples, validators, civic data integrations, explainers.'},
  {name:'LibreHealth', cause:'Health', tech:['PHP','Java','Health IT'], skills:['Backend','Health IT','Docs','QA'], url:'https://librehealth.io/', repo:'https://github.com/LibreHealthIO', blurb:'Community for free/open source Health IT projects under the Software Freedom Conservancy umbrella.', good:'EHR bugs, docs, tests, issue triage, health workflows.'},
  {name:'Benetech', cause:'Accessibility', tech:['Java','JavaScript','Accessibility'], skills:['Accessibility','Frontend','Mobile','Docs'], url:'https://benetech.org/', repo:'https://github.com/benetech', blurb:'Tech nonprofit with accessible reading and education tools, including open repositories around accessible books and media.', good:'Accessibility audits, reader UX, docs, educational tooling, data cleanup.'}
];
const skillMap = [
  ['Backend / distributed systems','Health records, lab systems, APIs, data pipelines, sync, imports, queues, reliability.'],
  ['Frontend / UX','Forms, maps, dashboards, mobile layouts, accessibility, onboarding flows, screenshots.'],
  ['Data / ML','Open data cleanup, deduping, schema validation, analytics, visualization, quality checks.'],
  ['Security / privacy','Threat modeling, dependency review, auth flows, secrets handling, safe deployment docs.'],
  ['DevOps / infra','Docker, CI, release scripts, monitoring examples, reproducible local setup.'],
  ['Docs / teaching','Setup guides, glossary pages, issue explainers, maintainer-friendly examples.'],
  ['GIS / mapping','OpenStreetMap, PostGIS, crisis maps, validation, map UX, field data.'],
  ['Mobile','Offline forms, Android collectors, barcode scanning, field constraints, accessibility.']
];
const grid = document.getElementById('projectGrid');
const causeFilter = document.getElementById('causeFilter');
const skillFilter = document.getElementById('skillFilter');
const techFilter = document.getElementById('techFilter');
const searchFilter = document.getElementById('searchFilter');
function unique(values){return [...new Set(values.flat())].sort();}
function addOptions(select, values){ values.forEach(v=>{const o=document.createElement('option'); o.value=v; o.textContent=v; select.appendChild(o);});}
addOptions(causeFilter, unique(projects.map(p=>[p.cause]))); addOptions(skillFilter, unique(projects.map(p=>p.skills))); addOptions(techFilter, unique(projects.map(p=>p.tech)));
function render(){
 const q = searchFilter.value.toLowerCase();
 const filtered = projects.filter(p => (causeFilter.value==='all'||p.cause===causeFilter.value) && (skillFilter.value==='all'||p.skills.includes(skillFilter.value)) && (techFilter.value==='all'||p.tech.includes(techFilter.value)) && (!q || JSON.stringify(p).toLowerCase().includes(q)));
 grid.innerHTML = filtered.map(p=>`<article class="project-card"><div class="project-top"><span>${p.cause}</span><h3>${p.name}</h3></div><p>${p.blurb}</p><div class="tags">${[...p.tech,...p.skills.slice(0,3)].map(t=>`<em>${t}</em>`).join('')}</div><p class="good"><strong>Good first angle:</strong> ${p.good}</p><div class="card-links"><a href="${p.url}" target="_blank" rel="noreferrer">Site</a><a href="${p.repo}" target="_blank" rel="noreferrer">Repo</a></div></article>`).join('') || '<p class="empty">No matches yet. Try clearing a filter.</p>';
}
[causeFilter,skillFilter,techFilter,searchFilter].forEach(el=>el.addEventListener('input',render)); render();
document.getElementById('skillMap').innerHTML = skillMap.map(([k,v])=>`<div><strong>${k}</strong><p>${v}</p></div>`).join('');
// parallax mouse
let mx=0,my=0; document.addEventListener('pointermove', e=>{mx=(e.clientX/window.innerWidth-.5); my=(e.clientY/window.innerHeight-.5); document.querySelectorAll('.parallax').forEach(el=>{const s=Number(el.dataset.speed||.05)*100; el.style.transform=`translate3d(${mx*s}px,${my*s}px,0)`;});});
// particles canvas
const canvas=document.getElementById('sky'), ctx=canvas.getContext('2d'); let dpr=1, parts=[];
function resize(){dpr=Math.min(devicePixelRatio||1,2); canvas.width=innerWidth*dpr; canvas.height=innerHeight*dpr; canvas.style.width=innerWidth+'px'; canvas.style.height=innerHeight+'px'; ctx.setTransform(dpr,0,0,dpr,0,0); parts=Array.from({length:Math.min(90,Math.floor(innerWidth/16))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:1+Math.random()*4,v:.15+Math.random()*.55,a:Math.random()*Math.PI*2,kind:Math.random()}));}
function draw(){ctx.clearRect(0,0,innerWidth,innerHeight); for(const p of parts){p.y-=p.v; p.x+=Math.sin(p.a+=.006)*.25 + mx*.25; if(p.y<-20){p.y=innerHeight+20;p.x=Math.random()*innerWidth;} ctx.globalAlpha=.22 + p.kind*.28; ctx.beginPath(); if(p.kind>.65){ctx.ellipse(p.x,p.y,p.r*1.8,p.r*.8,p.a,0,Math.PI*2);} else {ctx.arc(p.x,p.y,p.r,0,Math.PI*2);} ctx.fillStyle=p.kind>.65?'#1f9f7a':'#ffd27a'; ctx.fill(); } requestAnimationFrame(draw);} addEventListener('resize',resize); resize(); draw();
